title: "Code & Analyze: Arpita's Dev Blog"
description: "Daily logs of my learning journey in Software Development and Data Analysis."
author: Arpita Singh
email: arpitasi3332@gmail.com
theme: jekyll-theme-minimal
# Site navigation (menu)
header_pages:
  - index.md
  - blog-setup.md
  - about.md
